### ISSUE TITLE
Scrollbar doesn't match the theme.

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/GameShow#13]
During signup and in the leaderboard menu a scroll bar appears which doesnt match the theme. Change that.

Refer the link below for help:
[https://css-tricks.com/custom-scrollbars-in-webkit/](url)

**Comment by itaditya** [comment]
Ok Sir ,I'll fix that but the solution can only be done for Chrome , not for Firefox .

**Comment by abhayraw1** [comment]
Not working on chrome also.

**Comment by itaditya** [comment]
Sir it's working on Ankit and mine in ubuntu as well as windows , do you have the latest version of chromium?

**Comment by itaditya** [comment]
![image](https://cloud.githubusercontent.com/assets/15871340/19020113/cf3b5180-88bc-11e6-9f0f-8fd7342aeb73.png)
