### ISSUE TITLE
Increase the timeout delay for messages.

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/GameShow#14]
Upon answering the question  the user is shown a success or a failure message. The time duration for which the message is displayed is very short. Make sure you give ample of time so that the user is acually able to read it.

**Comment by itaditya** [comment]
Ok Sir , I have made the alert hold for 4s is it fine ?

**Comment by DEVAbhinav** [comment]
no 4s seems to much reduce it to 3000

**Comment by itaditya** [comment]
ok SIR DONE
