### ISSUE TITLE
layout of the laederboard page

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/GameShow#15]
The leaderboard page should be fixed (is scroll-able in the current scenario). The internal div housing the table should be scroll-able.

This similar functionality has been implemented in the rules page. Try to implement it in the leaderboard page also.

**Comment by itaditya** [comment]
Sir I have fixed this also , please check in yours

**Comment by abhayraw1** [comment]
Why is the scroll bar still present on the right?

**Comment by itaditya** [comment]
Sir mere system me sahi aa rha hai , maine to body tag ki height 100vh kar di hai and us par overflow hidden lgaya hai , so it is not possible , unless your browser is old and not support height as 100vh
