### ISSUE TITLE
The percentage in the dash should be dynammic.

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/GameShow#17]
The completion percentage of the user is independent of the number of levels of questions present in the db.
Make it more dynamic and dependent on the actual number of levels of questions.

**Comment by abhayraw1** [comment]
This has not been implemented yet. 
@DEVAbhinav take care of this.

**Comment by itaditya** [comment]
Sir it is working fine in our system, let me check thoroughly

**Comment by DEVAbhinav** [comment]
@itaditya I will tell you once Its implement this on backend.

**Comment by DEVAbhinav** [comment]
dynamic on the basis of levels
