### ISSUE TITLE
Also the year field takes inputs grater than 4 and less than one.

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/GameShow#22]

**Comment by ankitjain28may** [comment]
Sir, This field is validated.

**Comment by ankitjain28may** [comment]
![image](https://cloud.githubusercontent.com/assets/14014254/19019956/c895791e-88b7-11e6-8fa7-7d60f5f911be.png)

**Comment by itaditya** [comment]
Used min and max attribute in input also .

**Comment by itaditya** [comment]
Shall I close this one Sir ?

**Comment by abhayraw1** [comment]
Change the type from number to text with pattern [0-9]. 
It is accepting non integral values as well like 2.3 .

**Comment by itaditya** [comment]
Sir we can't use pattern , because the the data is sent via ajax requests and the form pattern validation only works when we hit the <input type="button"> but here there is no such thing

**Comment by ankitjain28may** [comment]
Shall i close this issue?
