### ISSUE TITLE
/login route improvement 

### ISSUE THREAD

**Issue by DEVAbhinav** [ncs-jss/GameShow#23]
1) At both login and register it seems as if caps are on remove it.
2) In register modal reference No also seems in caps  change it ..
3) In mobile view default /login is a bit scroll-able and that is of no use.
4) In mobile browser Signup modal covers up the entire page User cant go back to login modal as there is no way to close the signup modal other than page reload.

**Comment by ankitjain28may** [comment]
4- there is a close button on the modal to go back.

**Comment by ankitjain28may** [comment]
1- It is due to the font family, if font-family is changed, it will automatically come to default format.

**Comment by itaditya** [comment]
I have tried that caplock thing , I'm unable to find the reason , I have thought the problem would the `text-transform:uppercase` but it is not so , please help .

**Comment by itaditya** [comment]
Ok , I have found the problem of CAPSLOCK , the problem is font family used i.e. LemonMilk has only capital letters and no lowercase , thus we can't show that lowercase . So what should the replacement font should be ? @shivaniprakash95

**Comment by DEVAbhinav** [comment]
make that button more visible
