### ISSUE TITLE
Use HTML regex in form fields

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/GameShow#4]
Use regular expression in HTML form fields to restrict user from entering invalid characters in fields like mobile number and reference number.

**Comment by abhayraw1** [comment]
HTML regex is still not implemented..

**Comment by itaditya** [comment]
Sir the form is not send , instead the fields are inputted and then checked with regex (in js) and sent via ajax , so the pattern attribute in html doesn't do any thing , that's why we have used regex in js instead . Can I close the issue now ?

**Comment by abhayraw1** [comment]
Okay.
